services:
  - postgresql
language: ruby
rvm:
  - 2.3.1
before_script: 
  - gem install rake
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake parallel:create parallel:load_schema parallel:prepare
