default: &default
      adapter: postgresql
      encoding: sql_ascii
      pool: 5
      username: postgres
      password: password1
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production